# Rainbow, a termination proof certification tool
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2010-11-15

MAIN := xsd2ml

FILES := util error libxml xsd scc xsd_of_xml ml_of_xsd

FRAGILE_FILES := xsd ml_of_xsd

LIBS := xml-light/xml-light

INCLUDES := -I xml-light

libxml.cmo libxml.cmx : WARNINGS = -w -45

include Makefile.ocaml
