#!/bin/sh

# Rainbow, a termination proof certification tool
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2008-11-07

prog=`basename $0`

usage () { echo "usage: $prog [-h] [-saxon saxon.jar] [-ext file_extension] [-xsl aprove2ext.xsl] file.aprove"; }

help () {
  cat <<EOF
Produce a file.ext (or file.prf if no file extension is given)
from a file.aprove using aprove2ext.xsl (or $aprove_xsl if not given)
and saxon.jar (or $saxon_jar if not given).

Options:
-h Provide this help and exit
EOF
}

args () { echo 'error: wrong number of arguments'; usage; exit 1; }

saxon_jar=~/src/saxonb9-1-0-2j/saxon9.jar
ext=cpf
aprove_xsl=`dirname $0`/aproveToCPF.xsl

while true
do
  case "$1" in
  -h) usage; echo; help; exit 0;;
  -saxon) if test $# -lt 2; then args; else saxon_jar=$2; shift 2; fi;;
  -xsl) if test $# -lt 2; then args; else aprove_xsl=$2; shift 2; fi;;
  -ext) if test $# -lt 2; then args; else ext=$2; shift 2; fi;;
  *) break;;
  esac
done

if test $# -ne 1; then args; fi

case $1 in
*.aprove) base=${1%.aprove};;
*) echo 'error: unknown file type'; exit 1;;
esac

if grep -q MAYBE $base.out
then
  echo "ERROR: $base.out is MAYBE"
  exit 1
fi

java -jar $saxon_jar $base.aprove $aprove_xsl > $base.$ext
status=$?

if test $status -ne 0
then
  rm -f $base.$ext
  echo "ERROR $status"
  exit $status
fi

if test ! -s $base.$ext
then
  rm -f $base.$ext
  echo "ERROR: $base.$ext empty"
  exit 1
fi

if grep -q '<proof/>' $base.$ext
then
  rm -f $base.$ext
  echo "ERROR: $base.$ext has no proof"
  exit 1
fi
