#!/bin/sh

# Rainbow, a termination proof certification tool
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2009-06-02

prog=`basename $0`

usage () { echo "usage: $prog [-h] log_file"; }

help () {
  cat <<EOF
Computes statistics from a log file generated with get_log.

Options:
-h Provide this help and exit
EOF
}

args () { echo 'error: wrong number of arguments'; usage; exit 1; }

case "$1" in
-h) usage; echo; help; exit 0;;
esac

if test $# -ne 1; then args; fi

log=$1

`dirname $0`/../bin/get_stat < $log
