#!/bin/sh

# Rainbow, a termination proof certification tool
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2009-02-10

prog=`basename $0`

usage () { echo "usage: $prog [-h] file.prf"; }

help () {
  cat <<EOF
Produce a file.v from a file.prf. Requires that file.pb exists.

Options:
-h Provide this help and exit
EOF
}

args () { echo 'error: wrong number of arguments'; usage; exit 1; }

case "$1" in
-h) usage; echo; help; exit 0;;
esac

if test $# -ne 1; then args; fi

case $1 in
*.prf) base=${1%.prf};;
*) echo 'error: unknown file type'; exit 1;;
esac

if test ! -f $base.pb; then echo "error: no file $base.pb"; exit 1; fi
if test ! -f $base.prf; then echo "error: no file $base.prf"; exit 1; fi

`dirname $0`/../bin/prf2coq $base.pb $base.prf > $base.v
status=$?

if test $status -ne 0; then rm -f $base.v; exit $status; fi
