#!/bin/sh

# Rainbow, a termination proof certification tool
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2007-05-29

prog=`basename $0`

usage () { echo "usage: $prog [-h] file.[trs|srs|xtc|xml]"; }

help () {
  cat <<EOF
Produce file.pb from file.[trs|srs|xtc|xml]

Options:
-h Provide this help and exit
EOF
}

args () { echo 'error: wrong number of arguments'; usage; exit 1; }

case "$1" in
-h) usage; echo; help; exit 0;;
esac

if test $# -ne 1; then args; fi

input=$1

case $input in
*.xml) cmd=xtc2pb; base=${input%.xml};;
*.xtc) cmd=xtc2pb; base=${input%.xtc};;
*.trs) cmd=trs2pb; base=${input%.trs};;
*.srs) cmd=srs2pb; base=${input%.srs};;
*) echo 'error: unknown file type'; exit 1;;
esac

`dirname $0`/../bin/$cmd < $input > $base.pb
status=$?

if test $status -ne 0; then rm -f $base.pb; exit $status; fi
