#!/bin/sh

# Rainbow, a termination proof certification tool
# See the COPYRIGHTS and LICENSE files.
#
# - Frederic Blanqui, 2009-10-21

prog=`basename $0`

usage () { echo "usage: $prog [-h] file.xsd"; }

help () {
  cat <<EOF
Given an XML Schema file.xsd, generate an OCaml file.ml providing
an OCaml type definition representing the schema, and a function converting
an Xml.xml value (Xml-Light module) into this OCaml type.

Options:
-h Provide this help and exit
EOF
}

args () { echo 'error: wrong number of arguments'; usage; exit 1; }

case "$1" in
-h) usage; echo; help; exit 0;;
esac

if test $# -ne 1; then args; fi

case $1 in
*.xsd) base=${1%.xsd};;
*) echo "error: $1: unknown file type"; usage; exit 1;;
esac

`dirname $0`/../bin/xsd2ml < $1 > $base.ml
